name: "安昙のDiary"
permalink: /:title

author: "安昙小太郎"
atom-baseurl: "https://test007.gq"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Telegram
    class: fa fa-telegram
    href: //t.me/Kotaro007
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true