# Jekyll configuration

name: 安昙小太郎
description: Software Developer

url: http://test007.gq
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/'

social:
  #github: 
  twitter: 
  #stackoverflow: 
  #linkedin: 
  #codepen: 
  #instagram: 
  #lastfm: 
  rss: feed.xml
  telegram: test01_007

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

collections:
  quicknotes:
    output: false

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-106553302-2
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrika: true
# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: test007-gq
comments: true

permalink: /:title
gems: [jekyll-paginate]
paginate: 10

#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

plugins:
  - jekyll-feed

exclude: ['README.md', 'LICENSE', vendor]